### ISSUE TITLE
pending client won't wake up when using prepared statement

### ISSUE THREAD

**Issue by ycdeng** [postgrespro/postgresql.builtin_pool#12]
Hi, I'm testing builtin-pool.
The problem is channel_read() function of proxy.c.
When using prepared statement, a message contains multiple commands, for example, "Parse", "Bind" ... . If a client execute prepared statement and wait for free backend, on condition "Backend was not assigned", only the first command , for example ,"Parse" will be sent when pending client is served.
therefore, the backend is waiting for next command from client , and client is waiting for the respond from backend.

**Comment by knizhnik** [comment]
Thank you for reporting the problem.
Fix by commit 4e7eb6a

**Comment by ycdeng** [comment]
it's ok now.
thank you
