### ISSUE TITLE
try to connection different database caush pool crash

### ISSUE THREAD

**Issue by twelve1995** [postgrespro/postgresql.builtin_pool#9]
[pool crash.pdf](https://github.com/postgrespro/postgresql.builtin_pool/files/2238536/pool.crash.pdf)

**Comment by 1100hk** [comment]
but if I do the following:
`session_pool_size=2
session_pool_ports=1`

sessionA
`postgres@ubuntu:/home/hk/builtinpool/bin$ ./psql -d temp1 -p 5433
psql (11devel)
Type "help" for help.

temp1=# select pg_backend_pid();
 pg_backend_pid 
----------------
          43358
(1 row)

`

**Comment by knizhnik** [comment]
Sorry, I do not completely understand your concern.
As I already mentioned, it is not possible to connect to the same session pool (connection port) using more than one database/user. Is your complaint about server restart in this case? Commit f4c7b33 should fix it.

**Comment by twelve1995** [comment]
yes,My confusion is the server restart in this case.Thank you
